# Generated by Django 5.0.6 on 2026-09-04 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custody', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnchorTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Broadcast'), ('CONFIRMED', 'Confirmed on Blockchain'), ('FAILED', 'Broadcast Failed')], default='PENDING', max_length=20)),
                ('network', models.CharField(default='chipnet', max_length=50)),
                ('op_return_payload', models.CharField(blank=True, max_length=255)),
                ('block_height', models.IntegerField(blank=True, null=True)),
                ('block_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('explorer_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anchor_tx', to='custody.custodyevent')),
            ],
        ),
    ]
