# Generated by Django 5.0.6 on 2026-09-04 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_uid', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(default='General Cargo', max_length=100)),
                ('status', models.CharField(choices=[('IN_TRANSIT', 'In Transit'), ('STORED', 'Stored / In Warehouse'), ('DELIVERED', 'Delivered'), ('FLAGGED_TAMPERED', 'Flagged as Tampered')], default='IN_TRANSIT', max_length=30)),
                ('owner_wallet_address', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Handler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(default='Custodian', max_length=100)),
                ('badge_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('wallet_address', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustodyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('location', models.CharField(default='Checkpoint Alpha', max_length=255)),
                ('device_id', models.CharField(default='ESP32-NODE-01', max_length=100)),
                ('reed_switch_triggered', models.BooleanField(default=False)),
                ('accel_shock_detected', models.BooleanField(default=False)),
                ('tamper_status', models.CharField(choices=[('CLEAN', 'No Tampering Detected'), ('TAMPERED_REED', 'Enclosure Breached (Reed Switch)'), ('TAMPERED_SHOCK', 'Physical Impact Detected (MPU6050 Accelerometer)'), ('TAMPERED_MULTIPLE', 'Multiple Tamper Signals Detected')], default='CLEAN', max_length=30)),
                ('payload_hash', models.CharField(db_index=True, max_length=64)),
                ('signature', models.TextField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('is_anchored', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='custody.asset')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='custody.handler')),
            ],
        ),
    ]
